# Generated by Django 5.2.10 on 2026-01-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(default="Hello world!"),
        ),
    ]
