# Generated by Django 5.2.10 on 2026-01-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_course_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="subtitle",
            field=models.TextField(default="Subtitle"),
        ),
    ]
