# Generated by Django 5.2.10 on 2026-01-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_course_subtitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
    ]
