# Generated by Django 5.2.10 on 2026-01-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_remove_course_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="title",
        ),
    ]
