# Generated by Django 5.2.10 on 2026-01-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_rename_name_course_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Course",
            new_name="Subject",
        ),
    ]
