# Generated by Django 5.2.10 on 2026-01-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_rename_course_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="subtitle",
            new_name="secondary_title",
        ),
    ]
