# Generated by Django 5.2.10 on 2026-01-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_rename_subtitle_subject_secondary_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="lastname",
            new_name="last_name",
        ),
    ]
