# Generated by Django 5.2.10 on 2026-01-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_rename_firstname_member_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="secondary_title",
        ),
    ]
