# Generated by Django 5.2.10 on 2026-01-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_remove_subject_secondary_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subject",
            new_name="Course",
        ),
    ]
